# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6593b8a03769c435f6a78f0cd28eee6662e13e9b6724fd47b93e76cf001598e74df85dca8b1c41e90f8cb7f3725eb1d1af2e25213f070b170423751caa880345

test:
  secret_key_base: 29d7b3976d17446a5ded3a85bc0c8d6e015cd467ce3dcdf9535a0efe27322fa744d4870414a883f6b250680e05e485d04505f3c7a2b6e70c6840391d65c60bb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
